
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.PlainDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dante
 */
public class Credito extends javax.swing.JFrame {
    
    
    
    
     public HashMap<String, Float> cuotas = new HashMap<String,Float>(){{
        put("1",1.0f); 
        put("3",1.1f); 
        put("6",1.2f); 
        put("12",1.4f); 
        put("18",1.5f); 
    }};
    
    /**
     * Creates new form Debito
     */
    public Credito() {
        initComponents();
        mostrarFactura();
        Globales.setTicket(txtDebito.getText());
        inicializar();
        txtPrecioCuota.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDebito = new javax.swing.JTextArea();
        txtCuota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JTextField();
        txtPrecioCuota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        Pagar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbCuota = new javax.swing.JComboBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 129, 129));

        jLabel5.setText("Total:    $");

        txtDebito.setBackground(new java.awt.Color(219, 244, 248));
        txtDebito.setColumns(20);
        txtDebito.setRows(5);
        jScrollPane1.setViewportView(txtDebito);

        txtCuota.setEditable(false);
        txtCuota.setBackground(new java.awt.Color(115, 148, 148));

        jLabel3.setText("Precio por cuota:                  $");

        txtTarjeta.setBackground(new java.awt.Color(115, 148, 148));
        txtTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarjetaActionPerformed(evt);
            }
        });
        txtTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTarjetaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTarjetaKeyReleased(evt);
            }
        });

        txtPrecioCuota.setBackground(new java.awt.Color(115, 148, 148));

        jLabel1.setText("N° Tarjeta:");

        jLabel2.setText("Codigo:");

        txtCodigo.setBackground(new java.awt.Color(115, 148, 148));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });

        Pagar.setBackground(new java.awt.Color(153, 247, 247));
        Pagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pagar.png"))); // NOI18N
        Pagar.setText("Pagar");
        Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarActionPerformed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(153, 247, 247));
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/volver.png"))); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jLabel4.setText("Cuotas:");

        cmbCuota.setBackground(new java.awt.Color(115, 148, 148));
        cmbCuota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "3", "6", "12", "18" }));
        cmbCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCuotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(cmbCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Volver)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecioCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volver)
                    .addComponent(Pagar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Comprar abrir= new Comprar();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarActionPerformed
        // TODO add your handling code here:
        //float f = Float.valueOf(txtTarjeta.getText().trim()).floatValue();
        
        
        if (txtTarjeta.getText().length()==16 && txtCodigo.getText().length()==4) {
            PrinterJob printerJob = PrinterJob.getPrinterJob();
            printerJob.setPrintable(txtDebito.getPrintable(null, null));
        
            if(printerJob.printDialog()){
            try{
                printerJob.print();
            }catch(PrinterException ex){
                System.out.println("Error: "+ex);
            }
            }
            
            JOptionPane.showMessageDialog(null,"Compra realizada","Completo",JOptionPane.INFORMATION_MESSAGE);
            Ventana abrir= new Ventana();
            abrir.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Numero de tarjeta incorrecto","Error",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_PagarActionPerformed

    private void cmbCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuotaActionPerformed
        // TODO add your handling code here:
        cmbCuota.getSelectedItem();
        txtCuota.setText(""+getPrecio());
        
        txtPrecioCuota.setText(""+getPrecio()/getCuota());
        txtDebito.setText(Globales.getTicket()+"\n\nTotal con interes: $"+txtCuota.getText()+"\nPrecio de Cuota: $"+txtPrecioCuota.getText() );
        inicializar();
    }//GEN-LAST:event_cmbCuotaActionPerformed

    private void txtTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarjetaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTarjetaActionPerformed

    private void txtTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarjetaKeyTyped
       
    }//GEN-LAST:event_txtTarjetaKeyTyped

    private void txtTarjetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarjetaKeyReleased
        byte cero = '0';
        byte nueve = '9';
        char llega=evt.getKeyChar();
        String str ="";
        //OPCION 1
        /*
        if ((llega>=cero && llega<=nueve) || evt.getKeyCode() == 8){
            System.out.println("Es numero");
        }else{
            
            str = txtTarjeta.getText().substring(0, txtTarjeta.getText().length()-1);
            txtTarjeta.setText(str);            
            System.out.println("Es letra u otra cosa: " + evt.getKeyCode());
        }
        */
        //OPCION 2
        char[] letras = txtTarjeta.getText().toCharArray();
        for (int i = 0; i < letras.length; i++) {
            if (letras[i]>=cero && letras[i]<=nueve){
               str+=letras[i]; 
            }
            if (i>=15)
                break;
        }
        txtTarjeta.setText(str);
        
        
    }//GEN-LAST:event_txtTarjetaKeyReleased

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
        byte cero = '0';
        byte nueve = '9';
        char llega=evt.getKeyChar();
        String string ="";
        
        
        char[] a = txtCodigo.getText().toCharArray();
        for (int i = 0; i < a.length; i++) {
            if (a[i]>=cero && a[i]<=nueve){
               string+=a[i]; 
            }
            if (i>=3)
                break;
        }
        txtCodigo.setText(string);
    }//GEN-LAST:event_txtCodigoKeyReleased

    
     public void mostrarFactura(){
         String texto;
         String texto2;
         txtDebito.setText("");
        try{
            FileReader lector = new FileReader("archivo.txt");
            FileReader lector2 = new FileReader("persona.txt");
            BufferedReader contenido = new BufferedReader(lector);
            BufferedReader contenido2 = new BufferedReader(lector2);
            while((texto=contenido.readLine())!=null )
                txtDebito.setText(txtDebito.getText()+"\n"+texto);
            while((texto2=contenido2.readLine())!=null )
                txtDebito.setText(txtDebito.getText()+"\n"+texto2);
            
            txtDebito.setText(txtDebito.getText()+"\n\nTotal: $"+Globales.getPrecioTotal());
            
        }catch(Exception e){
            
        }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pagar;
    private javax.swing.JButton Volver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbCuota;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextArea txtDebito;
    private javax.swing.JTextField txtPrecioCuota;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
    private void inicializar() {       
        cmbCuota.removeAllItems();   
        cmbCuota.addItem("Cuotas");
        for(Map.Entry<String, Float> entry : cuotas.entrySet()) {
            cmbCuota.addItem(entry.getKey());

        }       
        
     cmbCuota.setSelectedIndex(0);
    }


    private float getPrecio(){
        String ropa = (String)cmbCuota.getSelectedItem();
        float precio = 0.0f;
        for(Map.Entry<String, Float> itemCuota : cuotas.entrySet()) {
            if(itemCuota.getKey().equals(ropa))
            {
                precio = itemCuota.getValue();
                
            }
            
        }
        return (precio*Globales.getPrecioTotal());
    }
    
    private float getCuota(){
        String ropa = (String)cmbCuota.getSelectedItem();
        String precio;
        float f=0.0f;
        for(Map.Entry<String, Float> itemCuota : cuotas.entrySet()) {
            if(itemCuota.getKey().equals(ropa))
            {
                precio = itemCuota.getKey();
                f = Float.parseFloat(precio);
                
            }
            
        }
        return (f);
    }
}
