
import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter.Entry;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dante
 */
public class Encargar extends javax.swing.JFrame {
    
    
    
    public HashMap<String, Float> talles = new HashMap<String,Float>(){{
        put("S",1.0f); 
        put("M",1.2f); 
        put("L",1.3f); 
        put("XL",1.4f); 
        put("XXL",1.5f); 
        
    }};
    
    
    
    public HashMap<String, Float> prendas = new HashMap<String,Float>(){{
        put("Pantalon",150f); 
        put("Remera",130f); 
        put("Short",110f); 
        put("Buzo",200f); 
        put("Campera",250f); 
        
    }};
    
    public HashMap<String, Float> style = new HashMap<String,Float>(){{
        put("Deporte",1.1f); 
        put("Moda",1.2f); 
        put("Diario",1.0f);
    }};
    
    /**
     * Creates new form Encargar
     */
    public  Encargar() {        
        initComponents();
        inicializar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTotal = new javax.swing.JTextArea();
        cmbTalle = new javax.swing.JComboBox();
        Limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmbRopa = new javax.swing.JComboBox();
        cmbEstilo = new javax.swing.JComboBox();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPrecioAct = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));
        setForeground(new java.awt.Color(0, 51, 255));

        jPanel2.setBackground(new java.awt.Color(2, 129, 129));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(219, 244, 248));
        txtTotal.setColumns(20);
        txtTotal.setRows(5);
        jScrollPane1.setViewportView(txtTotal);

        cmbTalle.setBackground(new java.awt.Color(115, 148, 148));
        cmbTalle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "S", "M", "L", "XL", "XXL" }));
        cmbTalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTalleActionPerformed(evt);
            }
        });

        Limpiar.setBackground(new java.awt.Color(153, 247, 247));
        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/escoba.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("Estilo:");

        cmbRopa.setBackground(new java.awt.Color(115, 148, 148));
        cmbRopa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pantalon", "Remera", "Short", "Buzo", "Campera" }));
        cmbRopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRopaActionPerformed(evt);
            }
        });

        cmbEstilo.setBackground(new java.awt.Color(115, 148, 148));
        cmbEstilo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Deporte", "Moda", "Diario" }));
        cmbEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstiloActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(153, 247, 247));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Talle:");

        jLabel5.setText("$");

        jLabel3.setText("Tipo de Ropa:");

        jButton1.setBackground(new java.awt.Color(153, 247, 247));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bien.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(153, 247, 247));
        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/volver.png"))); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Volver)
                                .addGap(53, 53, 53)
                                .addComponent(jButton1)
                                .addGap(101, 101, 101))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbRopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cmbEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel5)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtPrecioAct, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(Limpiar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbRopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(cmbEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbTalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPrecioAct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limpiar)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Volver)
                            .addComponent(jButton1))))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(662, 662, 662)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        Ventana abrir= new Ventana();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtTotal.getText().trim();
        if (txtTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"No hay compra","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            Comprar abrir= new Comprar();
            abrir.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (getPrecio()!=0){

            String variable = txtTotal.getText();
            txtTotal.setText( variable +"Prenda: " + cmbRopa.getSelectedItem()
                + " - Estilo: " + cmbEstilo.getSelectedItem()
                + " - Talle: " + cmbTalle.getSelectedItem()
                + " - Precio: $" + getPrecio()+"\n");
            Globales.incrementarTotal(getPrecio());
        }
        else{
            
            JOptionPane.showMessageDialog(null,"No compĺeto su pedido","Error",JOptionPane.ERROR_MESSAGE);
        }

        try{
            if(getPrecio()!=0 ){
                File archivo = new File ("archivo.txt");
                FileWriter escribir = new FileWriter(archivo, true);
                escribir.write((String) "Ropa:   "+cmbRopa.getSelectedItem()+"\n"
                    + "Estilo:     "+cmbEstilo.getSelectedItem()+"\n"
                    + "Talle:     "+cmbTalle.getSelectedItem()+"\n"
                    +"Precio:    "+"$"+(int) getPrecio()+"\n"+"---------------------------------"+"\n");
                escribir.close();}

        }
        catch (Exception e){
            System.out.println("Nada");
        }

        art.add(new Articulo((String) cmbRopa.getSelectedItem(), (String) cmbEstilo.getSelectedItem(), (String) cmbTalle.getSelectedItem(), getPrecio()));

        inicializar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstiloActionPerformed
        // TODO add your handling code here:
        cambiaPrecio();
    }//GEN-LAST:event_cmbEstiloActionPerformed

    private void cmbRopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRopaActionPerformed
        cambiaPrecio();
    }//GEN-LAST:event_cmbRopaActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        txtTotal.setText("");
        Globales.setPrecioTotal(0);
        File archivo = new File ("archivo.txt");
        archivo.delete();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void cmbTalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTalleActionPerformed
        cambiaPrecio();
    }//GEN-LAST:event_cmbTalleActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Volver;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox cmbEstilo;
    private javax.swing.JComboBox cmbRopa;
    private javax.swing.JComboBox cmbTalle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtPrecioAct;
    private javax.swing.JTextArea txtTotal;
    // End of variables declaration//GEN-END:variables
    private final ArrayList<Articulo> art = new ArrayList();
    private void inicializar() {       
        cmbRopa.removeAllItems();   
        cmbRopa.addItem("Seleccione un item");
        for(Map.Entry<String, Float> entry : prendas.entrySet()) {
            cmbRopa.addItem(entry.getKey());

        }                    
        
        cmbTalle.removeAllItems();        
        cmbTalle.addItem("Seleccione un talle");
        for(Map.Entry<String, Float> entry : talles.entrySet()) {
            cmbTalle.addItem(entry.getKey());
        }
         cmbEstilo.removeAllItems();        
        cmbEstilo.addItem("Seleccione un estilo");
        for(Map.Entry<String, Float> entry : style.entrySet()) {
            cmbEstilo.addItem(entry.getKey());
        
        }    
            
        cmbRopa.setSelectedIndex(0);
        cmbTalle.setSelectedIndex(0);
        cmbEstilo.setSelectedIndex(0);
        
    }

    

    private float getPrecio(){
        String ropa = (String)cmbRopa.getSelectedItem();
        String talle = (String)cmbTalle.getSelectedItem();
        String estilo = (String)cmbEstilo.getSelectedItem();
        float precio = 0.0f;
        float mod_talle = 0.0f;
        float mod_estilo = 0.0f;
        for(Map.Entry<String, Float> itemPrenda : prendas.entrySet()) {
            if(itemPrenda.getKey().equals(ropa))
            {
                precio = itemPrenda.getValue();
                
            }
            
        }
        for(Map.Entry<String, Float> itemEstilo : style.entrySet()) {
            if(itemEstilo.getKey().equals(estilo))
            {
                mod_estilo = itemEstilo.getValue();                
            }            
        }
        
        for(Map.Entry<String, Float> itemTalle : talles.entrySet()) {
            if(itemTalle.getKey().equals(talle))
            {
                mod_talle = itemTalle.getValue();                
            }            
        }
        return  (precio * mod_talle * mod_estilo);
        
    }
    
    private void cambiaPrecio() {        
         txtPrecioAct.setText("" + getPrecio());
        
    }
}
